DELETE http://localhost:8080/events/1/register
content-type: application/application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyMkBleGFtcGxlLmNvbSIsImV4cCI6MTc5MDQ4NzMxOCwidXNlcklkIjoyfQ.YvjwGFGQGo9sIax6Lr-MwvfPbXOXxCVd72RtDatQUEY