POST http://localhost:8080/events
content-type: application/application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3OTA0ODY4MzIsInVzZXJJZCI6MX0.4fdJeFEEDYuIpPA1cMM_CL-lOC2dM4mZq2eD8ftz5PU

{
    "name": "Test event",
    "description": "Test",
    "location": "A location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}