POST http://localhost:8080/events
content-type: application/application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzkwNDg0ODg4LCJ1c2VySWQiOjJ9.SGQvHCUs_azbDt-WYjMaipfpc0-1ETVPHDjX5lzxt-o

{
    "name": "Test event",
    "description": "Test",
    "location": "A location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}